lib/twi_master.h File Reference
#include <avr/io.h>
*
#include <util/twi.h>
*
#include <avr/interrupt.h>
*
#include <stdio.h>
*
#include <stdbool.h>
*
Macros
#define TWI_TWBR_VALUE_400 3
#define TWI_TWBR_VALUE_100 18
#define TWI_TWBR_VALUE_25 78
#define TWI_TWPS_VALUE 1
#define BUFFER_SIZE 10
Functions
void twi_master_init ()
Setup the twi module.
void twi_send_data (uint8_t slave, uint8_t anz_bytes)
Method to send data to a slave.
void twi_receive_data (uint8_t slave, uint8_t anz_bytes)
Corresponding to send_data this method receives data the same way.
void twi_master_set_ready ()
Variables
volatile uint8_t twi_receive_buffer [BUFFER_SIZE]
volatile uint8_t twi_send_buffer [BUFFER_SIZE]
Macro Definition Documentation
#define BUFFER_SIZE 10
Definition at line 10 of file twi_master.h.
#define TWI_TWBR_VALUE_100 18
Defines the TWBR value for 100 kHz TWI operation
Definition at line 2 of file twi_master.h.
Referenced by twi_master_init().
#define TWI_TWBR_VALUE_25 78
Definition at line 3 of file twi_master.h.
#define TWI_TWBR_VALUE_400 3
Defines the TWBR value for 400 kHz TWI operation
Definition at line 1 of file twi_master.h.
#define TWI_TWPS_VALUE 1
The prescaler is always 1 correspondig to the following equation:
 SCL frequency = CPU clock / 16 + 2 * TWBR * (4 ^ TWPS)
Definition at line 4 of file twi_master.h.
Function Documentation
void twi_master_init ()
Setup the twi module.
This function sets up the twi module for master operation. Therefore we have to write proper values to the following registers:
TWBR Two Wire Bitrate Register
TWSR Two Wire Status Register
TWCR Two Wire Control Register
TWBR and TWSR are used to configure the bus clock speed. The TWI specifications allows us to choose between two different clock speed modes: one below 100kHz and one up to 400kHz.
 The following equation shows how to set up the clock speed:
SCL frequency = CPU clock / 16 + 2 * TWBR * (4 ^ TWPS)
According to the equation we choosed TWBR = 18 and TWSR = 1 for 100kHz operations.
TWBR = TWI_TWBR_VALUE_100;
TWSR &= 0b11111100;
TWSR |= 0x01;
 As we can see in this tiny code fragment, the TWPS value is encoded by the two last bits of the TWSR register.
Definition at line 36 of file twi_master.c.
References TWI_TWBR_VALUE_100.
void twi_master_set_ready ()
Definition at line 162 of file twi_master.c.
References ready.
Referenced by bma020_read_raw_acceleration().
void twi_receive_data (uint8_t slave, uint8_t anz_bytes)
Corresponding to send_data this method receives data the same way.
Parameters
slave contains the slave adress
anz_bytes contains the amount of bytes that have to be transmitted
A global receive_buffer is used to store data that is received by TWI.
extern void receive_data(uint8_t slave, uint8_t anz_bytes)
{
    ready = FALSE;
    transmitter = FALSE;
    sla = slave;
    number_of_bytes = anz_bytes;
    rindx = 0;
    TWCR = (1<<TWINT) | (1<<TWSTA) | (1<<TWEN) | (1<<TWIE);
    while(!ready){}
}
 The only differences:
transmitter is set to FALSE
Instead of sindex we set rindex to zero.
Definition at line 151 of file twi_master.c.
References number_of_bytes, ready, rindx, sla, and transmitter.
Referenced by bma020_read_raw_acceleration().
void twi_send_data (uint8_t slave, uint8_t anz_bytes)
Method to send data to a slave.
Parameters
slave contains the slave adress
anz_bytes contains the amount of bytes that have to be transmitted
The data to be transmitted is stored in the global variable send_buffer. send_buffer[] is an array of uint8_t types. It's size is defined by the constant BUF_SIZE. The declaration of send_buffer is located in the twi_master.h file.
If one wants to transmit data to a slave, he has to write the data to the send_buffer. After calling the send_data() method, all bytes from send_buffer[0] to send_buffer[anz_bytes - 1] will be transmitted to the slave without interruption.
extern void send_data(uint8_t slave, uint8_t anz_bytes)
{
    ready = false;
    transmitter = true;
    sla = slave;
    number_of_bytes = anz_bytes;
    sindx = 0;
    TWCR = (1<<TWINT) | (1<<TWSTA) | (1<<TWEN) | (1<<TWIE);
    while(!ready){}
}
 Code explanation in detail:
ready = false;
 The ready variable is used to guarantee, that the whole transmission of every bytes is done without interruption. The program flow within the main method of this master controller is halted until all bytes have been transmitted.
transmitter = true;
 By setting the variable transmitter to TRUE, the ISR of the master controller can determine wether Master Transmitter or Master Receiver mode is active.
sla = slave;
 Store the slave adress in the global variable sla to make it visible for the ISR. Same with anz_bytes.
sindx = 0;
 Set the send_buffer index to zero.
TWCR = (1<<TWINT) | (1<<TWSTA) | (1<<TWEN) | (1<<TWIE);
 Here we can see how to manipulate the Two Wire Control Register.
TWINT causes the TWI to trigger an interrupt so that the ISR executes.
TWSTA cause the TWI to put a start signal on the TWI bus. All attached slave will recognize the start signal.
TWEN enables the TWI.
TWIE Two Wire Interrupt Enable allows the TWI to trigger interrupts.
while(!ready){}
The ready flag is set within the ISR when the TWI reaches an end state that indicates that the
      transmission
has finished.
Definition at line 115 of file twi_master.c.
References number_of_bytes, ready, sindx, sla, and transmitter.
Referenced by bma020_read_raw_acceleration().
Variable Documentation
volatile uint8_t twi_receive_buffer[BUFFER_SIZE]
Definition at line 5 of file twi_master.c.
Referenced by bma020_read_raw_acceleration(), and ISR().
volatile uint8_t twi_send_buffer[BUFFER_SIZE]
Definition at line 6 of file twi_master.c.
Referenced by bma020_read_raw_acceleration(), and ISR().